blank_issues_enabled: false
contact_links:
  - name: Flutter Journey Community Support
    url: https://github.com/orgs/Flutter-Journey/discussions
    about: Please ask and answer questions here.
  - name: Flutter Journey Encouraging Messages
    url: https://github.com/Flutter-Journey/.github/issues/1#issuecomment-new
    about: You should inspire the Flutter developer community here.