blank_issues_enabled: false
contact_links:
  - name: Flutter Journey Community Support
    url: https://github.com/Flutter-Journey/.github/issues/1#issuecomment-new
    about: Please ask and answer questions here.